### ISSUE TITLE
How to use alias

### ISSUE THREAD

**Issue by alanformstone** [quantumsheep/sshs#102]
I see that the Alias column could be really useful, but i cant find anywhere under ssh_config where to specify an alias. On the readme I see the Hello, but nothing in the sample .ssh/config. How do i use the Alias?

Many thanks, super useful!

**Comment by quantumsheep** [comment]
Aliases are the names matching the host's name. For example:
```
Host void name1 name2
  HostName 1.2.3.4
  User root
  Port 22
```

In this example aliases would be `name1` and `name2`.

**Comment by alanformstone** [comment]
Well I had no idea!!! Thank you very much.

**Comment by quantumsheep** [comment]
No problem! Hope you like sshs :)
