### ISSUE TITLE
Insufficient installation process?

### ISSUE THREAD

**Issue by Plaenkler** [quantumsheep/sshs#14]
2022/02/22 20:53:25 open C:\Users\*****\.ssh\config: The system cannot find the specified path.

Appears after "**successful**" installation on Win 10 Pro 64 bit

**Comment by quantumsheep** [comment]
You must have the `~/.ssh/config` file in order for sshs to work. The table is generated using this file.

**Comment by Plaenkler** [comment]
On Windows, the OpenSSH client creates the corresponding files only after first use. Can't SSHS create the .ssh directory and its contents itself? Just an idea.

**Comment by quantumsheep** [comment]
Agreed. It would completely get rid of that error message.

**Comment by Plaenkler** [comment]
Still does not work. Testet 2.1.1

![Error](https://user-images.githubusercontent.com/60503970/155476613-3d12e400-bf02-4b28-83d7-0f42069c9196.PNG)

**Comment by quantumsheep** [comment]
Woops, `path` module doesn't work with Windows paths for reasons. a6d75776e9852fe2db1b5a79a539fdccd99f2fba fixes the issue, provided in [release 2.1.2](https://github.com/quantumsheep/sshs/releases/tag/2.1.2).

**Comment by Plaenkler** [comment]
Still does not work. Tested 2.1.2

![Error](https://user-images.githubusercontent.com/60503970/155570159-05105217-75f8-4e86-a4ba-18eaf5896de2.PNG)

**Comment by Plaenkler** [comment]
Yes works fine thank you!
