### ISSUE TITLE
fulltext search

### ISSUE THREAD

**Issue by fichte** [quantumsheep/sshs#16]
it would be nice to have fulltext search :)

**Comment by quantumsheep** [comment]
What do you mean by fulltext search ?

**Comment by JConan** [comment]
Maybe he mean to search on every field.
In my case that would be useful as the target hostname is define in the user name (Cyberark) and all is pointing to the same target (bastion like pattern I guess)

**Comment by lunics** [comment]
And like fzf, able to find from a fuzzy request.

**Comment by quantumsheep** [comment]
Hey! This feature will be available in the next release. In the meantime you can build the project to use it.
