### ISSUE TITLE
Can't delete search term in CMD

### ISSUE THREAD

**Issue by yzaguirre** [quantumsheep/sshs#2]
This happens when running `sshs` in CMD, PowerShell or Git Bash, so mainly Windows 10.

For example, I type _tablet_ and I get the filtered list, but pressing delete button the field doesn't respond.

I confirm the search field works perfectly on Termux and Ubuntu.

Greetings

**Comment by quantumsheep** [comment]
I successfully reproduced it - will check tomorrow.

**Comment by livesamarthgupta** [comment]
Yes, but it does delete by pressing and holding ctrl and then pressing delete. It could be a workaround here.

**Comment by quantumsheep** [comment]
Windows backspace's seems to work like <kbd>Ctrl</kbd> + <kbd>Backspace</kbd> for whatever reason.

**Comment by yzaguirre** [comment]
I just learned that keyboard shortcut from here. That fashion works for CMD and PowerShell window.

**Comment by quantumsheep** [comment]
It should be fixed in 1.4.1, can you confirm it ?

**Comment by yzaguirre** [comment]
Version 1.4.1 is working without pressing CTRL

:thumbsup:
