### ISSUE TITLE
FeatReq: sorting of entries

### ISSUE THREAD

**Issue by ghoffart** [quantumsheep/sshs#21]
A command line option for sshs like `--sort` would be nice to have, so that similar named entries are next to each other while browsing with the cursor keys.

My .ssh/config has a lot of entries like

GroupNameA-ServerName1
GroupNameA-ServerName2
GroupNameA-ServerName3
GroupNameB-ServerName1

but not necessarily in this order in the config file. I could manually sort it, but …

**Comment by quantumsheep** [comment]
Sorting by default and having a `--no-sort` option might be better - will implement.
