### ISSUE TITLE
[BUG] 3.1.0 doesn’t sort host names

### ISSUE THREAD

**Issue by ghoffart** [quantumsheep/sshs#25]
`goetz@Wintermute ~ % sshs -v`
`sshs version 3.1.0`
(installed via `brew` on macOS 12.3.1/arm64)

According to the commit history of 3.1.0 this version should sort the hosts by name, but it doesn’t seem to be the case:

<img width="57" alt="grafik" src="https://user-images.githubusercontent.com/128098/166123524-0e884236-7b7c-4d3e-9b4c-5c53f6af1fcf.png">

**Comment by quantumsheep** [comment]
Hey! Can you try one of these artifacts ? https://github.com/quantumsheep/sshs/actions/runs/2254642136.

I'm not sure but that fixes some sorting issues on my side.
