### ISSUE TITLE
Support for Alias

### ISSUE THREAD

**Issue by Jalkar** [quantumsheep/sshs#28]
I have a server that posess multiple alias : 

```
Host server01 server_fonctionnality server@fqdn
        Hostname <IP>
        User <USER>
        Port 22
        IdentityFile ~/.ssh/<KEY>
```        

It seems that sshs try to access to a server named "server01 server_fonctionnality server@fqdn" instead of one of the 3 aliases

**Comment by quantumsheep** [comment]
I didn't know about multiple aliases, sshconfig has no real documentation so it's difficult to catch all specificities. I will fix it soon.

**Comment by anthony-francisco** [comment]
Hello.
I made it to take in count aliases :)

https://github.com/quantumsheep/sshs/pull/33

**Comment by quantumsheep** [comment]
@anthony-francisco thanks :)
