### ISSUE TITLE
Need an example config file

### ISSUE THREAD

**Issue by jarrodCoombes** [quantumsheep/sshs#3]
Trying to get this to work on MacOS after downloading the latest release. My config file is empty, hence the menu is as well. No idea what the format of this file should look like. Can you please upload an example of this file with details on how things should be entered into the file?

**Comment by jarrodCoombes** [comment]
Tack on to this a suggestion to make this somehow use the known_hosts file to populate the menu, that'd be pretty awesome.

**Comment by quantumsheep** [comment]
> Tack on to this a suggestion to make this somehow use the known_hosts file to populate the menu, that'd be pretty awesome.

Looking at my `known_hosts` file, the users are not in there. It would require to implement an input of some sort when trying to connect to a host that's not in the SSH config. Can you open another issue with this specific request so we can track it beyond the example file feature request ?
