### ISSUE TITLE
Error : x509 certificate signed by unknown authority

### ISSUE THREAD

**Issue by Azrod43** [quantumsheep/sshs#30]
Hello,

I want install sshs on Fedora 36. I use sources install.
At moment use command make I have this error :

![image](https://user-images.githubusercontent.com/92930647/173536926-542c504b-9cf9-4e5f-80fa-3ac2af65cff1.png)

And the librairie openssl-libs it's installed.

Do you have any ideas ?
Thanks

**Comment by quantumsheep** [comment]
Do you have the same issue with `wget https://gopkg.in/ini.v1\?go-get\=1 -O /dev/null`?

**Comment by quantumsheep** [comment]
I don't have the issue on my side, can you try installing [ca-certificates](https://src.fedoraproject.org/rpms/ca-certificates)? (`dnf install ca-certificates`)

**Comment by Azrod43** [comment]
This package it's already installed.

![image](https://user-images.githubusercontent.com/92930647/173582563-3cfe10b2-4153-4208-b727-2c2db36777f6.png)
The error comes from line 12 of the Makefile

![image](https://user-images.githubusercontent.com/92930647/173582694-3733d070-ac4e-4835-8fe7-d9d758f227da.png)

And go package it's alredy installed.

You think it may be another missing package ?

Thanks

**Comment by quantumsheep** [comment]
I don't think it's related to Go but your local configuration as you can't seem to be able to contact gopkg.in.

**Comment by Azrod43** [comment]
Okay, I have found my error..
It's my internal webfilter solution in my company who was blocking this site. I disabled this and now it's work.

Thanks for fast response.
