### ISSUE TITLE
Return to sshs page after logout

### ISSUE THREAD

**Issue by duylong** [quantumsheep/sshs#34]
Hi,

After an exit on the remote machine, we return to the source machine but without sshs. Is there a way to return directly to the sshs page? An operating mode like screen or tmux to always keep the active process in the foreground?

**Comment by atomotic** [comment]
I dislike this behavior, and rollbacked to 3.2.0. 
I would have preferred to have it configurable with a flag when launching sshs.

**Comment by quantumsheep** [comment]
We could add an option tho
