### ISSUE TITLE
How to exit? 

### ISSUE THREAD

**Issue by subzero911** [quantumsheep/sshs#39]
I can't exit the sshs utility.
"exit", Cmd+C not working. Only killing the terminal does.

**Comment by quantumsheep** [comment]
I suppose you're using macOS. On macOS you must use <kbd>Ctrl</kbd> + <kbd>C</kbd> instead of <kbd>Cmd</kbd> + <kbd>C</kbd>.

**Comment by subzero911** [comment]
Wow, it actually works!
I recently moved to Mac and not used to it 😊

**Comment by quantumsheep** [comment]
You'll love macOS once used to it! Enjoy sshs 🎉
