### ISSUE TITLE
Add an option to control if sshs should resume the UI after exiting an ssh session

### ISSUE THREAD

**Issue by quantumsheep** [quantumsheep/sshs#40]
Relates to https://github.com/quantumsheep/sshs/issues/34#issuecomment-1211686504.

**Comment by subzero911** [comment]
How to exit sshs window gracefully?
Currently, the only way I see is to close the terminal window, interrupting the running process.

**Comment by quantumsheep** [comment]
@subzero911 <kbd>Ctrl</kbd>+<kbd>C</kbd>.

**Comment by quantumsheep** [comment]
@subzero911 <kbd>Ctrl</kbd>+<kbd>C</kbd>

**Comment by subzero911** [comment]
It doesn't work on Mac

**Comment by subzero911** [comment]
Oh, sorry, it's actually `Control + C`
I pressed `Cmd+C`

**Comment by subzero911** [comment]
Could you add this shortcut into readme? It's easy to forget.
