### ISSUE TITLE
I changed the name of an item in my .ssh config, now it will no longer show up?

### ISSUE THREAD

**Issue by MostHated** [quantumsheep/sshs#41]
Hey there. 
  I am not quite sure what to do about this, but I changed the name of an item in my .ssh config and now it will no longer show up in sshs. I tried specifying --config ~/.ssh/config, just in case, but same result. All the other entries are there, just not the I renamed. I tried changing the name again, etc, but it just won't show up. Is there some sort of cache or something I need to clear out?

Thanks,
-MH

**Comment by MostHated** [comment]
I opened the file in vscode, formatted it, now it shows up. I guess I might have had an extra space somewhere in there? Not sure. My apologies for speaking to soon, though. :+1:

**Comment by quantumsheep** [comment]
No worries, I'm glad that worked at the end :)
