### ISSUE TITLE
windows: can't launch any ssh session with renamed exe

### ISSUE THREAD

**Issue by stf1966** [quantumsheep/sshs#42]
rename 'sshs-windows-amd64.exe' to 'sshs.exe' and you will not able to launch any session... You will just got the powershell or cmd prompt !

**Comment by stf1966** [comment]
Forget it
Apologies, wrong binary in my script: sshs-windows-386.exe instead sshs-windows-amd64.exe

**Comment by quantumsheep** [comment]
No worries, glad that it worked :)
