### ISSUE TITLE
Add the ability to ignore certain entries in the config file

### ISSUE THREAD

**Issue by kells64000** [quantumsheep/sshs#43]
If i have a file config with two entries like this :

```
Host gitlab
  HostName gitlab.com
  IdentityFile ~/.ssh/id_rsa
  User bob

Host server
  HostName server.com
  IdentityFile ~/.ssh/id_rsa
  User bob
    
```

When i execute sshs i want display only server.
Is this possible ?

**Comment by DeltaLima** [comment]
I guess splitting your servers into multiple config files and specifying the config for sshs wiht `--config` would do the trick.

**Comment by quantumsheep** [comment]
Like @DeltaLima said or you can use the search option:
```bash
sshs -s "server"
```

**Comment by kells64000** [comment]
Thank you, it's exactly what I needed!
