### ISSUE TITLE
Support for SSH alias

### ISSUE THREAD

**Issue by adrianmihalko** [quantumsheep/sshs#48]
I am using kitty and I would like to use it's own shell integration, so I need to use ssh like: kitty +kitten ssh name@host.

I created alias for this command:

alias ssh="kitty +kitten ssh"

I thought it might work from sshs, but it's not. Does sshs call ssh command directly from /usr/bin/ssh?

**Comment by BhaveshDiwan** [comment]
+1
My suggestion would be to be able to provide the binary, perhaps with it's flags via the config file (not the ssh config).

`$XDG_CONFIG_HOME/.sshs`
ssh_agent="/opt/homebrew/bin/kitty +kitten ssh"

**Comment by quantumsheep** [comment]
Hey! It's due to `os/exec` not using the shell but a child process directly.

There are solutions but not good solutions that will fit all cases. I might add an `--executable` option to pass anything you want to.

**Comment by quantumsheep** [comment]
Hey! In 4.0.0 I introduced `--template`, you can now do handlebars templating:
```
sshs --template "kitty +kitten ssh {{#if user}}{{user}}@{{/if}}{{destination}}{{#if port}} -p {{port}}{{/if}}"
```
