### ISSUE TITLE
Hostname is truncated if the name contains "["

### ISSUE THREAD

**Issue by Kerwood** [quantumsheep/sshs#5]
Hi. Thank you for this awesome and simple tool.

If a Hostname contains a `[` character, the last character in the hostname is removed.

![image](https://user-images.githubusercontent.com/4029521/152751541-271ae4cf-37f1-4ab0-85b1-3182dfcd259e.png)

![image](https://user-images.githubusercontent.com/4029521/152751616-d990dfdb-1dd8-4242-bf18-fcd21f141c45.png)

To reproduce, add the below hosts to your config.
```
Host "Host1 production"
  HostName example.org
  User username

Host "Host2 production]"
  HostName example.org
  User username

Host "Host3 [production]"
  HostName example.org
  User username

Host "Host4 [production"
  HostName example.org
  User username
```

**Comment by Kerwood** [comment]
It seems that if the `Host` ends with a space character you will not be able connect, see below.
```
Host "Host4 [production] "
...
```

Maybe you should trim

**Comment by quantumsheep** [comment]
`termui` is handling `[`, `]` but also `(` and `)` characters in a special way. This is very not wanted :/
https://github.com/gizak/termui/blob/4cca61d83fa2cc0f485c478ff768b0108f6591d6/v3/style_parser.go#L11-L24

Seems like there is no option to disable that so we might need to fork the library or switch to a complete other one.

**Comment by Kerwood** [comment]
Well, okay. It's not big deal, I thought it was a minor fix so just wanted to let you know :)
Thank you for looking into it.

**Comment by quantumsheep** [comment]
I will definitely fix it in the near future. I don't know how yet tho.
