### ISSUE TITLE
Support Vim Keybinds?

### ISSUE THREAD

**Issue by Ethnical** [quantumsheep/sshs#54]
Hello there, 
One cool feature can be to support Vim keybindings for navigating to ssh hosts.
Thanks for the current work like a charm!

**Comment by faileon** [comment]
Are there any plans for this feature? :)

**Comment by quantumsheep** [comment]
Hello! I'm not very familiar with Vim, what are the common keybinds?

**Comment by faileon** [comment]
> Hello! I'm not very familiar with Vim, what are the common keybinds?

Mainly h,j,k,l (left,down,up,right)

In case of sshs I'd be happy with ctrl+j and ctrl+k to move down and up.
