### ISSUE TITLE
[feature request] alpine

### ISSUE THREAD

**Issue by cirolosapio** [quantumsheep/sshs#58]
Is sshs currently available or planned to be made available on Alpine Linux? If not, are there any alternative packages or workarounds that can achieve a similar functionality?

**Comment by quantumsheep** [comment]
Hey! It wasn't planned but it doesn't seem that difficult, I will look into it when I have some time

**Comment by quantumsheep** [comment]
@cirolosapio do you think it's possible to add sshs in https://pkgs.alpinelinux.org/packages?
