### ISSUE TITLE
Wrong SHA256

### ISSUE THREAD

**Issue by stf1966** [quantumsheep/sshs#73]
sshs-windows-amd64.exe / sshs-windows-amd64.exe.sha256: v4.1.0 and v4.1.1 seems both wrong, v3.4.0 is ok

**Comment by stf1966** [comment]
Whoua, in fact my Windows 10 22H2 (19045.4046) move them in Quarantine (Win32/Wacapew.C!ml detected)

**Comment by quantumsheep** [comment]
Which method did you use to verify the checksum? It is generated in the CI using this PowerShell command:
```powershell
Get-FileHash -Algorithm SHA256 -Path "sshs-windows-amd64.exe" | Out-File -FilePath "sshs-windows-amd64.exe.sha256"
```

For the virus detection, sometimes Windows Defender prefer to put unknown executable in quarantine just in case. You can ensure your executable is virus-free using https://virustotal.com. [Here](https://www.virustotal.com/gui/file/ceca020a843d99f82cee80da9963a1a68337f9aae947bf7b5c51310ed728c2b5?nocache=1) is the scan for 4.1.1's Windows amd64 executable (which shows the same hash as the release artifact).

**Comment by stf1966** [comment]
Of course your CI is safe ;) Via Windows sanbox all the sha256 are ok (same method). My favorites 'bin' folder is now excluded from Defender scan. Sorry about this fake issue, my bad. Thanks and my best for this project
