### ISSUE TITLE
Hostname invalid

### ISSUE THREAD

**Issue by DamsPer** [quantumsheep/sshs#85]
Hello,

Since the last update I've an error with my config file. 

When I want tu connect to "My Server", I've this error : 
```
Running command: ssh "My Server"
hostname contains invalid characters
```

My config file : 
```
Host "My Server"
  HostName 1.1.1.1
  User test
  Port 22
```

**Comment by quantumsheep** [comment]
Hey! Which version of ssh are you using and on which operating system? `ssh -V`

**Comment by DamsPer** [comment]
Hello,

MacOs 14
SSh : OpenSSH_9.6p1, LibreSSL 3.3.6

**Comment by quantumsheep** [comment]
You may have strange characters in the host name, maybe try to rewrite the name manually in your config file?

**Comment by DamsPer** [comment]
I think is not the problem. 

sshs try connect to the "Host", not "hostName" in my config file.

A few time ago, I didn't have problem.

**Comment by DamsPer** [comment]
I try to rewrite manually but no change

**Comment by quantumsheep** [comment]
sshs is supposed to work like that, connecting to the Host and not the Hostname so it can be handled by ssh. However we have the same OpenSSH version so I'm not really sure what wrong...

How are you calling sshs?

**Comment by DamsPer** [comment]
I call sshs by `sshs -c ~/.ssh/config`

In example [here](https://github.com/quantumsheep/sshs?tab=readme-ov-file#troubleshooting), the "Host" value is anything but the "hostName" is the fqdn of server.

**Comment by DamsPer** [comment]
Not strange charaters...

**Comment by quantumsheep** [comment]
Do you have the same issue with `1.1.1.1`?

**Comment by DamsPer** [comment]
ssh 1.1.1.1 ok
ssh "My Server" don't work because it's a friendly name, not fqdn or ip server.

I think "Host" attribute is a friendly name and ssh connect to the "hostName".

**Comment by quantumsheep** [comment]
What I meant is try with this config literally :
```nginx
Host "My Server"
  HostName 1.1.1.1
  User test
  Port 22
```

`ssh "My Server"` SHOULD work.

**Comment by DamsPer** [comment]
My config file is the same of you're and I've thos error : 
```
ssh "My Server"                                                                                                                                                                                                    
hostname contains invalid characters
```

**Comment by quantumsheep** [comment]
[Seems like a known issue](https://github.com/microsoft/vscode-remote-release/issues/9370#issuecomment-2019779256) but I don't have the issue even though I'm on the same macOS and OpenSSH version as you.

I suggest discussing the issue in https://github.com/microsoft/vscode-remote-release/issues/9370 as it's not a sshs issue.
