### ISSUE TITLE
Adding search based on IP Address

### ISSUE THREAD

**Issue by frant1** [quantumsheep/sshs#87]
Hello,

On the golang version I was able to search an entry based on the IP Address (and may be on any field).

Since I'm on the Rust version, it looks like this behavior isn't copied.

Would it be possible to have it ?

Thanks for your job !

**Comment by berrydamien** [comment]
Hello,
Yes also for me. 
In my case search an entry based on the IP Address is an essential option.
In version 3.4.0 the last in Go it's possible.
