### ISSUE TITLE
Option `-a` to forward argument

### ISSUE THREAD

**Issue by nodauf** [quantumsheep/sshs#88]
Hello,

In the Golang version, I used a lot the argument `-a` that allows to forward option to ssh (https://github.com/quantumsheep/sshs/pull/51).
Would it be possible to add the same argument on the rust version ?

Thank you

**Comment by quantumsheep** [comment]
Hello ! You can use the `--template` option:
```bash
sshs --template 'ssh "{{{name}}}" arg1 arg2'
```

Does that fit your need?

**Comment by nodauf** [comment]
Yes thank you I did not think about that.
