### ISSUE TITLE
Implement scrolling.

### ISSUE THREAD

**Issue by leeiitb** [quantumsheep/sshs#9]
We have more than a hundred host entries.
When we press the down arrow, the selector disappears after the first screen is over.
We would like to have the selector stay in view and move the host list up.

**Comment by leeiitb** [comment]
Working fine in 2.0.0.
Thanks a lot.

**Comment by leeiitb** [comment]
Cool .
One question.
How to exit if you do not want to select any host ?

**Comment by quantumsheep** [comment]
> Cool . One question. How to exit if you do not want to select any host ?

<kbd>Ctrl</kbd> + <kbd>C</kbd>

**Comment by leeiitb** [comment]
Thanks a lot 😎.
I was trying to type commands in the search bar, but forgot the obvious 😀.

**Comment by quantumsheep** [comment]
Do not hesitate if you have other questions 😄
